// Starting points. The plants and curves marked ABOP follow the L-systems
// printed in chapter 1 of Prusinkiewicz and Lindenmayer, "The Algorithmic
// Beauty of Plants" (1990), with their edge symbols Fl and Fr written as A
// and B; the other entries are standard textbook forms.

export const PRESETS = [
  {
    id: 'weed',
    name: 'Stochastic weed',
    group: 'Plants',
    note: 'ABOP section 1.7: three equally likely productions, so every seed is a different specimen.',
    axiom: 'F',
    rules: 'F (0.33) -> F[+F]F[-F]F\nF (0.33) -> F[+F]F\nF (0.34) -> F[-F]F',
    iterations: 5,
    angle: 25.7,
    draw: 'F',
  },
  {
    id: 'herb',
    name: 'Herb',
    group: 'Plants',
    note: 'ABOP figure 1.24a, edge rewriting.',
    axiom: 'F',
    rules: 'F -> F[+F]F[-F]F',
    iterations: 5,
    angle: 25.7,
    draw: 'F',
  },
  {
    id: 'sprig',
    name: 'Sprig',
    group: 'Plants',
    note: 'ABOP figure 1.24b, edge rewriting.',
    axiom: 'F',
    rules: 'F -> F[+F]F[-F][F]',
    iterations: 5,
    angle: 20,
    draw: 'F',
  },
  {
    id: 'shrub',
    name: 'Shrub',
    group: 'Plants',
    note: 'ABOP figure 1.24c, edge rewriting.',
    axiom: 'F',
    rules: 'F -> FF-[-F+F+F]+[+F-F-F]',
    iterations: 4,
    angle: 22.5,
    draw: 'F',
  },
  {
    id: 'reed',
    name: 'Reed',
    group: 'Plants',
    note: 'ABOP figure 1.24d, node rewriting: X marks a growing tip and F doubles each step.',
    axiom: 'X',
    rules: 'X -> F[+X]F[-X]+X\nF -> FF',
    iterations: 7,
    angle: 20,
    draw: 'F',
  },
  {
    id: 'sapling',
    name: 'Sapling',
    group: 'Plants',
    note: 'ABOP figure 1.24e, node rewriting.',
    axiom: 'X',
    rules: 'X -> F[+X][-X]FX\nF -> FF',
    iterations: 7,
    angle: 25.7,
    draw: 'F',
  },
  {
    id: 'fern',
    name: 'Fern',
    group: 'Plants',
    note: 'ABOP figure 1.24f, node rewriting.',
    axiom: 'X',
    rules: 'X -> F-[[X]+X]+F[+FX]-X\nF -> FF',
    iterations: 5,
    angle: 22.5,
    draw: 'F',
  },
  {
    id: 'koch-island',
    name: 'Quadratic Koch island',
    group: 'Curves',
    note: 'ABOP figure 1.6: each edge becomes an eight-segment generator.',
    axiom: 'F-F-F-F',
    rules: 'F -> F-F+F+FF-F-F+F',
    iterations: 3,
    angle: 90,
    draw: 'F',
  },
  {
    id: 'snowflake',
    name: 'Koch snowflake',
    group: 'Curves',
    note: 'Three Koch curves on the sides of a triangle.',
    axiom: 'F--F--F',
    rules: 'F -> F+F--F+F',
    iterations: 5,
    angle: 60,
    draw: 'F',
  },
  {
    id: 'dragon',
    name: 'Dragon curve',
    group: 'Curves',
    note: 'ABOP figure 1.10a: a strip of paper folded in half again and again.',
    axiom: 'A',
    rules: 'A -> A+B+\nB -> -A-B',
    iterations: 10,
    angle: 90,
    draw: 'AB',
  },
  {
    id: 'gasket',
    name: 'Sierpinski gasket',
    group: 'Curves',
    note: 'ABOP figure 1.10b: one unbroken path that traces the gasket.',
    axiom: 'B',
    rules: 'A -> B+A+B\nB -> A-B-A',
    iterations: 6,
    angle: 60,
    draw: 'AB',
  },
  {
    id: 'gosper',
    name: 'Hexagonal Gosper curve',
    group: 'Curves',
    note: 'ABOP figure 1.11a: a space-filling curve that tiles a fractal hexagon.',
    axiom: 'A',
    rules: 'A -> A+B++B-A--AA-B+\nB -> -A+BB++B+A--A-B',
    iterations: 4,
    angle: 60,
    draw: 'AB',
  },
  {
    id: 'hilbert',
    name: 'Hilbert curve',
    group: 'Curves',
    note: 'A and B only steer; F draws. Fills the square as the generations rise.',
    axiom: 'A',
    rules: 'A -> +BF-AFA-FB+\nB -> -AF+BFB+FA-',
    iterations: 5,
    angle: 90,
    draw: 'F',
  },
  {
    id: 'levy',
    name: 'Lévy C curve',
    group: 'Curves',
    note: 'Each segment becomes two at right angles, bowing outward.',
    axiom: 'F',
    rules: 'F -> +F--F+',
    iterations: 12,
    angle: 45,
    draw: 'F',
  },
];

export function findPreset(id) {
  return PRESETS.find((p) => p.id === id) ?? null;
}
